/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface PasswordlessLink {
        "buttonLabel": string;
        "channel": string;
        "clientId": string;
        "getIdTokenPayload": () => Promise<any>;
        "isAuthenticated": () => Promise<boolean>;
        "isPopup": boolean;
        "logout": () => Promise<void>;
        "tenantDomain": string;
    }
}
declare global {
    interface HTMLPasswordlessLinkElement extends Components.PasswordlessLink, HTMLStencilElement {
    }
    var HTMLPasswordlessLinkElement: {
        prototype: HTMLPasswordlessLinkElement;
        new (): HTMLPasswordlessLinkElement;
    };
    interface HTMLElementTagNameMap {
        "passwordless-link": HTMLPasswordlessLinkElement;
    }
}
declare namespace LocalJSX {
    interface PasswordlessLink {
        "buttonLabel"?: string;
        "channel"?: string;
        "clientId": string;
        "isPopup"?: boolean;
        "onAuthCompleted"?: (event: CustomEvent<boolean>) => void;
        "tenantDomain": string;
    }
    interface IntrinsicElements {
        "passwordless-link": PasswordlessLink;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "passwordless-link": LocalJSX.PasswordlessLink & JSXBase.HTMLAttributes<HTMLPasswordlessLinkElement>;
        }
    }
}
